export const ExperienceInfos = [
  {
    title: "SWE Internship",
    company: "Microsoft",
    organization: "Office Products",
    location: "Redmond, WA",
    time_range: "May 2025",
    description: `Returning intern on the Excel team in the Office organization. Contributing to the development of a new feature for Copilot in Excel with a focus on Python-based advanced analysis workflows. Collaborating with full-time engineers, designers, and product managers to deliver intelligent tooling that enhances data analysis in spreadsheets.`,
  },
  {
    title: "Software Subsystem Architecture Course Assistant",
    company: "Rochester Institute of Technology",
    organization: "Software Engineering Department",
    location: "Rochester, NY",
    time_range: "January 2025 - May 2025",
    description: `Supported students in learning and applying GoF design patterns within the context of large-scale software architecture. Assisted with UML modeling, system decomposition, and code reviews. Helped students understand the importance of modularity and maintainability in complex systems.`,
  },
  {
    title: "Head of Technology",
    company: "Rochester Institute of Technology",
    organization: "Society of Software Engineers",
    location: "Rochester, NY",
    time_range: "January 2024 - December 2024",
    description: `Led the redesign and deployment of the Society of Software Engineers' website (sse.rit.edu), managing a 37-member technical team. Directed full-stack development using Next.js, coordinated Git workflows, and mentored contributors in development practices and version control. Oversaw infrastructure and deployment on the organization’s self-hosted server.`,
  },
  {
    title: "Explorer Intern",
    company: "Microsoft",
    organization: "Office Products",
    location: "Redmond, WA",
    time_range: "May 2024 - August 2024",
    description: `Worked with two other Explorer interns on the Excel team, building a feature for Copilot in Excel. Gained experience in both Software Engineering and Product Management by collaborating in a triad structure. Conducted design research, prototyped the solution, and presented deliverables to full-time product teams.`,
  },
  {
    title: "Student Outreach Specialist",
    company: "Rochester Institute of Technology",
    organization: "Accessible Learning Labs",
    location: "Rochester, NY",
    time_range: "January 2024 - May 2024",
    description: `Represented Accessible Learning Labs (ALL) in outreach efforts to K–12 schools. Organized logistics and led hands-on presentations that introduced students to accessibility concepts in computing. Helped build relationships between schools and the ALL research initiative.`,
  },
  {
    title: "Software Development II Course Assistant",
    company: "Rochester Institute of Technology",
    organization: "Software Engineering Department",
    location: "Rochester, NY",
    time_range: "January 2024 - May 2024",
    description: `Provided support in a second-level programming course focused on Java, object-oriented design, advanced data structures, and introductory algorithms. Helped students debug, understand core concepts, and succeed on complex projects and assessments.`,
  },
  {
    title: "Head of Talks",
    company: "Rochester Institute of Technology",
    organization: "Society of Software Engineers",
    location: "Rochester, NY",
    time_range: "August 2023 - December 2023",
    description: `Coordinated volunteer-based long-form presentations within the Society of Software Engineers. Worked with student and faculty presenters to schedule sessions, promote attendance, and foster technical and non-technical community dialogue.`,
  },
  {
    title: "Software Development I Course Assistant",
    company: "Rochester Institute of Technology",
    organization: "Software Engineering Department",
    location: "Rochester, NY",
    time_range: "August 2023 - December 2023",
    description: `Assisted students learning introductory programming in Python, including control flow, functions, and basic algorithms. Provided 1-on-1 help during labs, answered questions on assignments, and offered tutoring during office hours.`,
  },
  {
    title: "SSE Mentor",
    company: "Rochester Institute of Technology",
    organization: "Society of Software Engineers",
    location: "Rochester, NY",
    time_range: "August 2023 - December 2023",
    description: `Volunteered as a mentor for new members of the Society of Software Engineers. Provided guidance on project contributions, Git practices, and how to get involved in technical and leadership opportunities within the organization.`,
  },
];
